version: '3.3'

services:  
  web-auth:
    image: auth
    build:
      context: ./auth
      dockerfile: Dockerfile
    volumes:
      - sharing-cookie-auth_keyring-conf:/app/keyRing
    ports:
      - "8435:8435"
    environment:
      KEY_RING_PATH: /app/keyRing

  web-app1:
    image: app1
    build:
      context: ./App1
      dockerfile: Dockerfile
    volumes:
      - sharing-cookie-auth_keyring-conf:/app/keyRing
    ports:
      - "8436:8436"
    environment:
      KEY_RING_PATH: /app/keyRing

  web-app2:
    image: app2
    build:
      context: ./App2
      dockerfile: Dockerfile
    volumes:
      - sharing-cookie-auth_keyring-conf:/app/keyRing
    ports:
      - "8437:8437"
    environment:
      KEY_RING_PATH: /app/keyRing

volumes:
  sharing-cookie-auth_keyring-conf: